version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Madrid
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: prisma
    ports:
      - 3366:3306
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
